spring:
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test  # H2 접속 정보
    username: qq10user  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: qq10 # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate:
      ddl: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate.SQL: debug
server:
  servlet:
    encoding:
      force-response: true
  port:
    8080
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
encrypt:
  secretKey: Ks2Jh7Ql1Xp9Vy3Tz8Ew5Rq6Oy9Pz0
#  access-token-expiration-minutes : 10000
#  refresh-token-expiration-minutes : 420